In [1]:
# import pandas library
import pandas as pd

# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}

# creating a Dataframe object
df = pd.DataFrame(details)
df

Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2    Shaurya   22         DU
3   Shivangi   21        BHU

In [4]:
# dictionary with list object in values
details = {
    0 : [1, 2, 3, 4],
    1 : [10, 11, 12, 13],
    2 : [20, 21, 22, 23],
}

# creating a Dataframe object
results = pd.DataFrame(details).transpose()
results

0   1   2   3
0   1   2   3   4
1  10  11  12  13
2  20  21  22  23

In [5]:
means = results.mean().values
means

array([10.33333333, 11.33333333, 12.33333333, 13.33333333])

In [7]:
stds = results.std().values
stds

array([9.50438495, 9.50438495, 9.50438495, 9.50438495])

In [9]:
import numpy as np

# dictionary with list object in values
details = np.array([[1, 2, 3, 4], [10, 11, 12, 13], [20, 21, 22, 23]])

# creating a Dataframe object
results2 = pd.DataFrame(details)
results2

0   1   2   3
0   1   2   3   4
1  10  11  12  13
2  20  21  22  23

In [13]:
isinstance(details, np.ndarray)

True

In [10]:
means = results2.mean().values
means

array([10.33333333, 11.33333333, 12.33333333, 13.33333333])

In [11]:
from multiprocessing import cpu_count

cpu_count()

8